//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsing_Service.FCTDEWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FCTDEWS.FCTDEWSSoap")]
    public interface FCTDEWSSoap {
        
        // CODEGEN: Generating message contract since element name DatiRichiesta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFCTDEReport", ReplyAction="*")]
        Parsing_Service.FCTDEWS.UploadFCTDEReportResponse UploadFCTDEReport(Parsing_Service.FCTDEWS.UploadFCTDEReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFCTDEReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Parsing_Service.FCTDEWS.UploadFCTDEReportResponse> UploadFCTDEReportAsync(Parsing_Service.FCTDEWS.UploadFCTDEReportRequest request);
        
        // CODEGEN: Generating message contract since element name DatiRichiesta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFCTDEParsedReport", ReplyAction="*")]
        Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponse UploadFCTDEParsedReport(Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFCTDEParsedReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponse> UploadFCTDEParsedReportAsync(Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFCTDEReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFCTDEReport", Namespace="http://tempuri.org/", Order=0)]
        public Parsing_Service.FCTDEWS.UploadFCTDEReportRequestBody Body;
        
        public UploadFCTDEReportRequest() {
        }
        
        public UploadFCTDEReportRequest(Parsing_Service.FCTDEWS.UploadFCTDEReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFCTDEReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DatiRichiesta;
        
        public UploadFCTDEReportRequestBody() {
        }
        
        public UploadFCTDEReportRequestBody(string DatiRichiesta) {
            this.DatiRichiesta = DatiRichiesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFCTDEReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFCTDEReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public Parsing_Service.FCTDEWS.UploadFCTDEReportResponseBody Body;
        
        public UploadFCTDEReportResponse() {
        }
        
        public UploadFCTDEReportResponse(Parsing_Service.FCTDEWS.UploadFCTDEReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFCTDEReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long UploadFCTDEReportResult;
        
        public UploadFCTDEReportResponseBody() {
        }
        
        public UploadFCTDEReportResponseBody(long UploadFCTDEReportResult) {
            this.UploadFCTDEReportResult = UploadFCTDEReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFCTDEParsedReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFCTDEParsedReport", Namespace="http://tempuri.org/", Order=0)]
        public Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequestBody Body;
        
        public UploadFCTDEParsedReportRequest() {
        }
        
        public UploadFCTDEParsedReportRequest(Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFCTDEParsedReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DatiRichiesta;
        
        public UploadFCTDEParsedReportRequestBody() {
        }
        
        public UploadFCTDEParsedReportRequestBody(string DatiRichiesta) {
            this.DatiRichiesta = DatiRichiesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFCTDEParsedReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFCTDEParsedReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponseBody Body;
        
        public UploadFCTDEParsedReportResponse() {
        }
        
        public UploadFCTDEParsedReportResponse(Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFCTDEParsedReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long UploadFCTDEParsedReportResult;
        
        public UploadFCTDEParsedReportResponseBody() {
        }
        
        public UploadFCTDEParsedReportResponseBody(long UploadFCTDEParsedReportResult) {
            this.UploadFCTDEParsedReportResult = UploadFCTDEParsedReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FCTDEWSSoapChannel : Parsing_Service.FCTDEWS.FCTDEWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FCTDEWSSoapClient : System.ServiceModel.ClientBase<Parsing_Service.FCTDEWS.FCTDEWSSoap>, Parsing_Service.FCTDEWS.FCTDEWSSoap {
        
        public FCTDEWSSoapClient() {
        }
        
        public FCTDEWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FCTDEWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCTDEWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCTDEWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parsing_Service.FCTDEWS.UploadFCTDEReportResponse Parsing_Service.FCTDEWS.FCTDEWSSoap.UploadFCTDEReport(Parsing_Service.FCTDEWS.UploadFCTDEReportRequest request) {
            return base.Channel.UploadFCTDEReport(request);
        }
        
        public long UploadFCTDEReport(string DatiRichiesta) {
            Parsing_Service.FCTDEWS.UploadFCTDEReportRequest inValue = new Parsing_Service.FCTDEWS.UploadFCTDEReportRequest();
            inValue.Body = new Parsing_Service.FCTDEWS.UploadFCTDEReportRequestBody();
            inValue.Body.DatiRichiesta = DatiRichiesta;
            Parsing_Service.FCTDEWS.UploadFCTDEReportResponse retVal = ((Parsing_Service.FCTDEWS.FCTDEWSSoap)(this)).UploadFCTDEReport(inValue);
            return retVal.Body.UploadFCTDEReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Parsing_Service.FCTDEWS.UploadFCTDEReportResponse> Parsing_Service.FCTDEWS.FCTDEWSSoap.UploadFCTDEReportAsync(Parsing_Service.FCTDEWS.UploadFCTDEReportRequest request) {
            return base.Channel.UploadFCTDEReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Parsing_Service.FCTDEWS.UploadFCTDEReportResponse> UploadFCTDEReportAsync(string DatiRichiesta) {
            Parsing_Service.FCTDEWS.UploadFCTDEReportRequest inValue = new Parsing_Service.FCTDEWS.UploadFCTDEReportRequest();
            inValue.Body = new Parsing_Service.FCTDEWS.UploadFCTDEReportRequestBody();
            inValue.Body.DatiRichiesta = DatiRichiesta;
            return ((Parsing_Service.FCTDEWS.FCTDEWSSoap)(this)).UploadFCTDEReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponse Parsing_Service.FCTDEWS.FCTDEWSSoap.UploadFCTDEParsedReport(Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest request) {
            return base.Channel.UploadFCTDEParsedReport(request);
        }
        
        public long UploadFCTDEParsedReport(string DatiRichiesta) {
            Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest inValue = new Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest();
            inValue.Body = new Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequestBody();
            inValue.Body.DatiRichiesta = DatiRichiesta;
            Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponse retVal = ((Parsing_Service.FCTDEWS.FCTDEWSSoap)(this)).UploadFCTDEParsedReport(inValue);
            return retVal.Body.UploadFCTDEParsedReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponse> Parsing_Service.FCTDEWS.FCTDEWSSoap.UploadFCTDEParsedReportAsync(Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest request) {
            return base.Channel.UploadFCTDEParsedReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Parsing_Service.FCTDEWS.UploadFCTDEParsedReportResponse> UploadFCTDEParsedReportAsync(string DatiRichiesta) {
            Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest inValue = new Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequest();
            inValue.Body = new Parsing_Service.FCTDEWS.UploadFCTDEParsedReportRequestBody();
            inValue.Body.DatiRichiesta = DatiRichiesta;
            return ((Parsing_Service.FCTDEWS.FCTDEWSSoap)(this)).UploadFCTDEParsedReportAsync(inValue);
        }
    }
}
